name: nutrabit_paciente
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  file_picker: ^10.1.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_data_connect: ^0.1.4+1
  firebase_storage: 12.4.5
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.6
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^29.2.4
  meta: ^1.9.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^3.1.0
  mockito: ^5.4.6
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  url_launcher_platform_interface: ^2.1.2
  riverpod_test: ^0.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/img/
