// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetcAEEAyHBPbbRW7X7M6hj2jjsacM2gw',
    appId: '1:977116124631:web:527efa6e5901b561b52792',
    messagingSenderId: '977116124631',
    projectId: 'nutrabit',
    authDomain: 'nutrabit.firebaseapp.com',
    storageBucket: 'nutrabit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fxWe_BrT17puFt-FNVuvBnhGZ3UPev4',
    appId: '1:977116124631:android:758e417cdec9479bb52792',
    messagingSenderId: '977116124631',
    projectId: 'nutrabit',
    storageBucket: 'nutrabit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAA9EpzEhgkbKEf8PhbgK0qwqBuEMfsU',
    appId: '1:977116124631:ios:a2d3a03b83e6e46db52792',
    messagingSenderId: '977116124631',
    projectId: 'nutrabit',
    storageBucket: 'nutrabit.firebasestorage.app',
    iosBundleId: 'com.example.nutrabitPaciente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGAA9EpzEhgkbKEf8PhbgK0qwqBuEMfsU',
    appId: '1:977116124631:ios:a2d3a03b83e6e46db52792',
    messagingSenderId: '977116124631',
    projectId: 'nutrabit',
    storageBucket: 'nutrabit.firebasestorage.app',
    iosBundleId: 'com.example.nutrabitPaciente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDetcAEEAyHBPbbRW7X7M6hj2jjsacM2gw',
    appId: '1:977116124631:web:c87d4c4e12ea5f35b52792',
    messagingSenderId: '977116124631',
    projectId: 'nutrabit',
    authDomain: 'nutrabit.firebaseapp.com',
    storageBucket: 'nutrabit.firebasestorage.app',
  );
}
