// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsWRBYaecVhDALW1Ico-gwfYWL4OkFfug',
    appId: '1:1018369904543:web:81f065db5d12e4278837aa',
    messagingSenderId: '1018369904543',
    projectId: 'nutrabit-7a4ce',
    authDomain: 'nutrabit-7a4ce.firebaseapp.com',
    storageBucket: 'nutrabit-7a4ce.firebasestorage.app',
    measurementId: 'G-Z9F4HS816P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVkgF_HiU4DxbbJnfMikt0pbh8j5ycvw',
    appId: '1:1018369904543:android:e27421020e40bfd38837aa',
    messagingSenderId: '1018369904543',
    projectId: 'nutrabit-7a4ce',
    storageBucket: 'nutrabit-7a4ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4fmud8Nytby7SS68sR7EmwpsAYFdjng',
    appId: '1:1018369904543:ios:101c1570fd4ffdc48837aa',
    messagingSenderId: '1018369904543',
    projectId: 'nutrabit-7a4ce',
    storageBucket: 'nutrabit-7a4ce.firebasestorage.app',
    iosBundleId: 'com.example.nutrabitPaciente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4fmud8Nytby7SS68sR7EmwpsAYFdjng',
    appId: '1:1018369904543:ios:101c1570fd4ffdc48837aa',
    messagingSenderId: '1018369904543',
    projectId: 'nutrabit-7a4ce',
    storageBucket: 'nutrabit-7a4ce.firebasestorage.app',
    iosBundleId: 'com.example.nutrabitPaciente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsWRBYaecVhDALW1Ico-gwfYWL4OkFfug',
    appId: '1:1018369904543:web:067731ffffe5589f8837aa',
    messagingSenderId: '1018369904543',
    projectId: 'nutrabit-7a4ce',
    authDomain: 'nutrabit-7a4ce.firebaseapp.com',
    storageBucket: 'nutrabit-7a4ce.firebasestorage.app',
    measurementId: 'G-P6XWXS1EMK',
  );

}