// Mocks generated by Mockito 5.4.6 from annotations
// in nutrabit_paciente/test/presentations/screens/password/forgot_password_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nutrabit_paciente/core/models/app_user.dart' as _i5;
import 'package:nutrabit_paciente/presentations/providers/auth_provider.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncNotifierProviderRef_1<T> extends _i1.SmartFake
    implements _i3.AsyncNotifierProviderRef<T> {
  _FakeAsyncNotifierProviderRef_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncValue_2<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthNotifier extends _i1.Mock implements _i4.AuthNotifier {
  MockAuthNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeFirebaseFirestore_0(this, Invocation.getter(#db)),
          )
          as _i2.FirebaseFirestore);

  @override
  _i3.AsyncNotifierProviderRef<_i5.AppUser?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAsyncNotifierProviderRef_1<_i5.AppUser?>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i3.AsyncNotifierProviderRef<_i5.AppUser?>);

  @override
  _i3.AsyncValue<_i5.AppUser?> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_2<_i5.AppUser?>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AsyncValue<_i5.AppUser?>);

  @override
  _i6.Future<_i5.AppUser?> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i6.Future<_i5.AppUser?>.value(),
          )
          as _i6.Future<_i5.AppUser?>);

  @override
  set state(_i3.AsyncValue<_i5.AppUser?>? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<bool> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isPacienteByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isPacienteByEmail, [email]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> updatePassword({
    required String? currentPassword,
    required String? newPassword,
    required String? repeatPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
              #repeatPassword: repeatPassword,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void listenSelf(
    void Function(_i3.AsyncValue<_i5.AppUser?>?, _i3.AsyncValue<_i5.AppUser?>)?
    listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i5.AppUser?> update(
    _i6.FutureOr<_i5.AppUser?> Function(_i5.AppUser?)? cb, {
    _i6.FutureOr<_i5.AppUser?> Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [cb], {#onError: onError}),
            returnValue: _i6.Future<_i5.AppUser?>.value(),
          )
          as _i6.Future<_i5.AppUser?>);

  @override
  bool updateShouldNotify(
    _i3.AsyncValue<_i5.AppUser?>? previous,
    _i3.AsyncValue<_i5.AppUser?>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
